version: '3'

services:

  xava-db:
    image: zhangyongjiang/xava-db-pianfang:${TAG}

  xava-search:
    image: zhangyongjiang/xava-search-pianfang:${TAG}
    ports: 
      - 8983:8983

  xava-server:
    image: zhangyongjiang/xava-server-pianfang:${TAG}
    depends_on:
      - xava-db
      - xava-search
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=docker
